#!/usr/bin/env python

"""
Conveniently run one of the commands provided in tests/conftest.py, see ./run --help
"""

import os
import subprocess
import sys


SCRIPT_PATH = os.path.abspath(__file__)
PROJECT_FOLDER = os.path.dirname(SCRIPT_PATH)
TESTS_FOLDER = os.path.join(PROJECT_FOLDER, "tests")


def try_venv(*paths):
    """Conveniently rerun this script from a venv, if possible (otherwise complain)"""
    for path in paths:
        folder = os.path.join(PROJECT_FOLDER, path)
        pyexe = os.path.join(folder, "bin", "python")
        if os.path.isfile(pyexe):
            args = [pyexe, SCRIPT_PATH] + sys.argv[1:]
            r = subprocess.run(args)
            sys.exit(r.returncode)
    sys.exit("Please build a venv first in one of: %s" % ", ".join(paths))


if not sys.exec_prefix.startswith(PROJECT_FOLDER):
    try_venv(".venv", ".tox/py37", ".tox/py36", ".tox/py27")


if TESTS_FOLDER not in sys.path:
    venv = os.path.join(sys.base_prefix, "bin")
    os.environ["PATH"] = "%s:%s" % (venv, os.environ["PATH"])
    sys.path.append(TESTS_FOLDER)


try:
    from . import conftest
except (ImportError, ValueError):
    import conftest


conftest.main()
