#!/usr/bin/env python

"""
Conveniently run one of the commands provided in tests/conftest.py, see ./run --help
"""

import os
import subprocess
import sys


SCRIPT_PATH = os.path.abspath(__file__)
PROJECT_FOLDER = os.path.dirname(SCRIPT_PATH)
RECURSION_MARKER = "--qqnr"

if "__PYVENV_LAUNCHER__" in os.environ:
    del os.environ["__PYVENV_LAUNCHER__"]  # See https://github.com/python/cpython/pull/9516

if not sys.exec_prefix.startswith(PROJECT_FOLDER):
    # We're not running from venv
    if RECURSION_MARKER in sys.argv:
        sys.exit("Something's wrong, recursive call")

    venvs = (".venv", ".tox/py39", ".tox/py27")
    for path in venvs:
        folder = os.path.join(PROJECT_FOLDER, path)
        pyexe = os.path.join(folder, "bin", "python")
        if os.path.isfile(pyexe):
            args = [pyexe, SCRIPT_PATH, RECURSION_MARKER] + sys.argv[1:]
            p = subprocess.Popen(args)
            p.communicate()
            sys.exit(p.returncode)

    sys.exit("Please build a venv first in one of: %s" % ", ".join(venvs))

if PROJECT_FOLDER not in sys.path:
    sys.path.append(PROJECT_FOLDER)

if RECURSION_MARKER in sys.argv:
    sys.argv.remove(RECURSION_MARKER)

from tests.conftest import main  # noqa

main()
