name: Simulate publishing to pypi

on:
  release:
    types: [created, published, released]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: |
        pip install -U pip setuptools wheel
        python setup.py sdist bdist_wheel --universal

    - run: ls -laF dist/
