# Run tests and linter

name: Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install -U pip tox
    - run: tox -e py
    - uses: actions/upload-artifact@v2
      with:
        name: junit-${{ matrix.python-version }}
        path: |
          .tox/.coverage.py
          .tox/py/junit.xml
      if: ${{ always() }}
  check-code-style:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/download-artifact@v2
      with:
        path: .tox/downloaded-artifacts
    - run: ls -laF .tox/downloaded-artifacts
    - run: pip install -U pip tox
    - run: tox -e docs,style
